Import Elvis 2.2_0 (written by Steve Kirkendall)

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,5 +1,5 @@
 # Makefile.in
-# $Id: Makefile.in,v 2.65 1999/10/20 18:30:01 steve Exp $
+# $Id: Makefile.in,v 2.121 2003/10/21 02:31:00 steve Exp $
 #
 # Makefile.in should not be modified!  The "configure" script reads Makefile.in
 # and writes a customized Makefile by editing the values of the following
@@ -13,7 +13,7 @@
 # both for compiling and for linking.  Typical values are "cc -g" or "cc -O".
 # If you're compiling with X-windows support, you may need to add a
 # "-I/usr/X11/include" flag or something similar.
-#CC=gcc -g -Wall -pedantic -Wtraditional -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes
+#CC=gcc -g -Wall -pedantic -Wtraditional -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -I/usr/include/freetype2 -I/usr/X11R6/include
 CC=cc -O
 
 ################################################################################
@@ -71,17 +71,22 @@ FLAGI=-I
 # ctags and elvtags are the same program under different names.  The $(EXE) on
 # the end is just in case this Makefile is reconfigured for an operating
 # system which requires the EXE macro to be something like ".exe".
-ALL=elvis$(EXE) ref$(EXE) elvtags$(EXE)
+ALL=elvis$(EXE) ref$(EXE) elvtags$(EXE) elvfmt$(EXE)
+
+################################################################################
+# The installation directories are relative to this
+PREFIX=/usr/local
 
 ################################################################################
 # This is the directory where "make install" will place the executable programs
-BINDIR=/usr/local/bin
+BINDIR=$(PREFIX)/bin
 
 ################################################################################
 # This is the directory where "make install" will place elvis' support files,
 # such as the help text and the default initialization scripts.  If you change
 # the value here, then you also need to change it in "config.h"
-LIBDIR=/usr/local/lib/elvis
+DATADIR=$(PREFIX)/share/elvis
+DOCDIR= $(PREFIX)/share/elvis/doc
 
 ################################################################################
 # This is the shell command for copying one file to another
@@ -102,8 +107,10 @@ CP=cp
 ###############################################################################
 # Portable compilation rules
 
+VERSION=2.2_0
 MISC=	BUGS README.html COPYING INSTALL Makefile.in configure instman.sh\
-	insticon.sh elvis.lsm makwin32.bat makmsdos.bat makos2.cmd e2
+	elvis.lsm makwin32.bat makmsdos.bat makos2.cmd e2 \
+	elvis.spec.in Announce-$(VERSION)
 OSSRCS=	os$(OS)$(SLASH)osblock.c os$(OS)$(SLASH)osdir.c\
 	os$(OS)$(SLASH)osprg.c os$(OS)$(SLASH)ostext.c\
 	os$(OS)$(SLASH)osnet.c os$(OS)$(SLASH)tcaphelp.c
@@ -116,33 +123,44 @@ X11SRCS=guix11/guix11.c guix11/xclip.c guix11/xevent.c guix11/xmisc.c\
 	guix11/xdialog.c
 X11OBJS=guix11$(OBJ) xclip$(OBJ) xevent$(OBJ) xmisc$(OBJ) xscroll$(OBJ)\
 	xstatus$(OBJ) xtext$(OBJ) xtool$(OBJ) xdialog$(OBJ)
-GUISRCS=$(X11SRCS) guicurs.c guitcap.c guiopen.c
-GUIOBJS=$(X11OBJS) guicurs$(OBJ) guitcap$(OBJ) guiopen$(OBJ)
+X11HDRS=guix11/guix11.h guix11/xclip.h guix11/xdialog.h guix11/xevent.h\
+	guix11/xmisc.h guix11/xscroll.h guix11/xstatus.h guix11/xtext.h\
+	guix11/xtool.h
+
+GNOMESRCS=guignome/guignome.c guignome/guignome_clip.c guignome/guignome_mousedrag.c guignome/elvisCorba-common.c guignome/elvisCorba-skels.c guignome/elvisCorba-stubs.c guignome/guignome_corba.c
+GNOMEOBJS=guignome/guignome$(OBJ) guignome/guignome_clip$(OBJ) guignome/guignome_mousedrag$(OBJ) guignome/elvisCorba-common$(OBJ) guignome/elvisCorba-skels$(OBJ) guignome/elvisCorba-stubs$(OBJ) guignome/guignome_corba$(OBJ)
+GHOMEHDRS=
+
+GUISRCS=$(GNOMESRCS) $(X11SRCS) guicurs.c guitcap.c guiopen.c
+GUIOBJS=$(GNOMEOBJS) $(X11OBJS) guicurs$(OBJ) guitcap$(OBJ) guiopen$(OBJ)
+GUIHDRS=$(GNOMEHDRS) $(X11HDRS)
 LPSRCS=	lpescape.c lpovrtyp.c lpps.c
 LPOBJS=	lpescape$(OBJ) lpovrtyp$(OBJ) lpps$(OBJ)
-HDRS=	$(OSHDRS) buffer.h buffer2.h calc.h cut.h digraph.h display.h\
-	display2.h draw.h draw2.h elvis.h elvisio.h event.h ex.h gui.h gui2.h\
-	input.h lowbuf.h lp.h map.h mark.h message.h message2.h misc.h more.h\
-	move.h need.h operator.h opsys.h optglob.h options.h regexp.h safe.h\
-	scan.h session.h state.h state2.h tag.h tagsrch.h tagelvis.h version.h\
-	vi.h vicmd.h window.h config.h
-SRCS=	$(OSSRCS) $(GUISRCS) $(LPSRCS) buffer.c calc.c cut.c digraph.c\
-	display.c dmhex.c dmmarkup.c dmnormal.c dmsyntax.c draw.c\
-	event.c ex.c exaction.c exconfig.c exedit.c exmake.c exsubst.c ftp.c\
-	gui.c http.c input.c io.c lowbuf.c lp.c map.c mark.c message.c misc.c\
-	more.c move.c need.c operator.c optglob.c options.c regexp.c regsub.c\
-	safe.c scan.c search.c session.c state.c tag.c tagsrch.c tagelvis.c\
-	url.c vi.c vicmd.c window.c
+HDRS=	$(OSHDRS) $(GUIHDRS) autocmd.h buffer.h buffer2.h calc.h color.h\
+	cut.h descr.h digraph.h display.h display2.h draw.h draw2.h elvis.h\
+	elvisio.h event.h ex.h gui.h gui2.h input.h lowbuf.h lp.h map.h\
+	mark.h message.h message2.h misc.h more.h move.h need.h operator.h\
+	opsys.h optglob.h options.h regexp.h region.h safe.h scan.h session.h\
+	spell.h state.h state2.h tag.h tagsrch.h tagelvis.h version.h vi.h\
+	vicmd.h window.h config.h
+SRCS=	$(OSSRCS) $(GUISRCS) $(LPSRCS) autocmd.c buffer.c calc.c color.c cut.c\
+	descr.c digraph.c display.c dmhex.c dmmarkup.c dmnormal.c dmsyntax.c\
+	draw.c event.c ex.c exaction.c exconfig.c exedit.c exmake.c exsubst.c\
+	fold.c ftp.c gui.c http.c input.c io.c lowbuf.c lp.c main.c map.c\
+	mark.c message.c misc.c more.c move.c need.c operator.c optglob.c\
+	options.c regexp.c region.c regsub.c safe.c scan.c search.c session.c\
+	spell.c state.c tag.c tagsrch.c tagelvis.c url.c vi.c vicmd.c window.c
 OBJ1=	$(OSOBJS) optglob$(OBJ) options$(OBJ) safe$(OBJ) session$(OBJ)
-OBJ2=	buffer$(OBJ) calc$(OBJ) digraph$(OBJ) display$(OBJ) gui$(OBJ)\
-	lowbuf$(OBJ) mark$(OBJ) misc$(OBJ) io$(OBJ) dmhex$(OBJ)\
-	dmmarkup$(OBJ) dmnormal$(OBJ) dmsyntax$(OBJ) scan$(OBJ)
-OBJ3=	$(OSOBJS2) cut$(OBJ) draw$(OBJ) event$(OBJ) ex$(OBJ) exaction$(OBJ)\
-	exconfig$(OBJ) exedit$(OBJ) exmake$(OBJ) exsubst$(OBJ) ftp$(OBJ)\
-	http$(OBJ) input$(OBJ) lp$(OBJ) map$(OBJ) message$(OBJ) move$(OBJ)\
-	more$(OBJ) need$(OBJ) operator$(OBJ) regexp$(OBJ) regsub$(OBJ)\
-	search$(OBJ) state$(OBJ) tinytcap$(OBJ) tag$(OBJ) tagsrch$(OBJ)\
-	tagelvis$(OBJ) url$(OBJ) vi$(OBJ) vicmd$(OBJ) window$(OBJ)
+OBJ2=	buffer$(OBJ) calc$(OBJ) color$(OBJ) descr$(OBJ) digraph$(OBJ)\
+	display$(OBJ) gui$(OBJ) lowbuf$(OBJ) mark$(OBJ) misc$(OBJ) io$(OBJ)\
+	dmhex$(OBJ) dmmarkup$(OBJ) dmnormal$(OBJ) dmsyntax$(OBJ) scan$(OBJ)
+OBJ3=	$(OSOBJS2) autocmd$(OBJ) cut$(OBJ) draw$(OBJ) event$(OBJ) ex$(OBJ)\
+	exaction$(OBJ) exconfig$(OBJ) exedit$(OBJ) exmake$(OBJ) exsubst$(OBJ)\
+	fold$(OBJ) ftp$(OBJ) http$(OBJ) input$(OBJ) lp$(OBJ) map$(OBJ)\
+	message$(OBJ) move$(OBJ) more$(OBJ) need$(OBJ) operator$(OBJ)\
+	regexp$(OBJ) region$(OBJ) regsub$(OBJ) search$(OBJ) spell$(OBJ)\
+	state$(OBJ) tinytcap$(OBJ) tag$(OBJ) tagsrch$(OBJ) tagelvis$(OBJ)\
+	url$(OBJ) vi$(OBJ) vicmd$(OBJ) window$(OBJ)
 OBJS=	$(OBJ1) $(OBJ2) $(OBJ3)
 REFOBJS=ref$(OBJ) tag$(OBJ) tagsrch$(OBJ) safe$(OBJ)
 CTOBJS=	ctags$(OBJ) tag$(OBJ) safe$(OBJ)
@@ -150,8 +168,8 @@ CFLAGS=	$(FLAGI)os$(OS)
 EVERY=	$(ALL) verify$(EXE) elvdump$(EXE) calc$(EXE)
 SHELL=	/bin/sh
 
-DISTRIB=elvis-2.1_4
-MSDOSEXE=exemsdos
+DISTRIB=elvis-$(VERSION)
+DOSEXE=exedos
 WIN32EXE=exewin32
 OS2EXE=exeos2
 
@@ -165,10 +183,16 @@ elvis$(EXE): $(HDRS) main$(OBJ) $(OBJS) $(GUIOBJS) $(LPOBJS)
 ctags$(EXE): $(CTOBJS)
 	$(CC) $(CFLAGS) $(CTOBJS) -o ctags$(EXE)
 
+doc/elvtags.man: doc/ctags.man
+	sed 's/\<CTAGS\>/ELVTAGS/g; s/ctags\>/elvtags/g; s/ant" elvtags/ant" ctags/' doc/ctags.man >doc/elvtags.man
+
 elvtags$(EXE): ctags$(EXE)
 	$(CP) ctags$(EXE) elvtags$(EXE)
-	sed 's/\<CTAGS\>/ELVTAGS/g; s/\<ctags\>/elvtags/g' lib/ctags.man >lib/elvtags.man
-	
+
+elvfmt$(EXE) doc/elvfmt.man: fmt$(EXE) doc/fmt.man
+	$(CP) fmt$(EXE) elvfmt$(EXE)
+	sed 's/\<FMT\>/ELVFMT/g; s/\<fmt\>/elvfmt/g' doc/fmt.man >doc/elvfmt.man
+
 ref$(EXE): $(REFOBJS)
 	$(CC) $(CFLAGS) $(REFOBJS) -o ref$(EXE)
 
@@ -237,21 +261,32 @@ xtool$(OBJ): guix11/xtool.c
 xdialog$(OBJ): guix11/xdialog.c
 	$(OSCC) guix11/xdialog.c
 
+guignome$(OBJ): guignome/guignome.c
+	$(OSCC) guignome/guignome.c
+
+guignome/elvisCorba-common.c: guignome/elvisCorba.idl
+	(cd guignome; orbit-idl elvisCorba.idl)
+
+guignome/elvisCorba-skels.c: guignome/elvisCorba-common.c
+guignome/elvisCorba-stubs.c: guignome/elvisCorba-common.c
+guignome/elvisCorba.h: guignome/elvisCorba-common.c
+
 ###############################################################################
 # Handy commands
 
 clean: clean.$(OS)
+	$(RM) $(ALL)
 
 clean.unix:
 	$(RM) *$(OBJ)
+	$(RM) guignome/*$(OBJ) guignome/elvisCorba-* guignome/elvisCorba.h
 	$(RM) core
 	$(RM) errlist
 	$(RM) verify.elv
+	$(RM) gdk_imlib.h
 	$(RM) $(DISTRIB).tar.gz
-	$(RM) lib/elvtags.man
-	$(RM) $(MSDOSEXE)/*
-	$(RM) $(WIN32EXE)/*
-	$(RM) $(OS2EXE)/*
+	$(RM) doc/elvtags.man
+	$(RM) elvis.rpm
 
 clean.msdos:
 	$(RM) *$(OBJ)
@@ -276,103 +311,155 @@ wc: $(SRCS) $(HDRS)
 	wc $(SRCS) $(HDRS) | sort -n
 
 tags: $(SRCS) $(HDRS)
-	ctags $(SRCS) $(HDRS)
+	elvtags $(SRCS) $(HDRS)
 
 ciall: $(SRCS) $(HDRS)
 	ci -u$(REV) Makefile $(SRCS) $(HDRS)
 
 cinever:
 	@for i in *.[ch]; do [ -f RCS/$$i,v ] || echo $$i; done
-	@for i in os*/.; do (cd $$i; for j in *.[ch]; do [ -f $$j,v -o -f RCS/$$j,v ] || echo $$i/$$j; done); done
-	@for i in gui*/.; do (cd $$i; for j in *.[ch]; do [ -f $$j,v -o -f RCS/$$j,v ] || echo $$i/$$j; done); done
+	@for i in os*/.; do (cd $$i; for j in *.[ch]; do [ -f $$j,v -o -f RCS/$$j,v ] || echo `dirname $$i`/$$j; done); done
+	@for i in gui*/.; do (cd $$i; for j in *.[ch]; do [ -f $$j,v -o -f RCS/$$j,v ] || echo `dirname $$i`/$$j; done); done
+
+tarball:
+	rm -f $(DISTRIB).tar.gz
+	make $(DISTRIB).tar.gz
 
 $(DISTRIB).tar.gz:
 	rm -rf $(DISTRIB)
 	mkdir $(DISTRIB)
-	mkdir $(DISTRIB)/lib
 	for i in os*; do if [ -d $$i ]; then mkdir $(DISTRIB)/$$i; fi; done
 	for i in gui*; do if [ -d $$i ]; then mkdir $(DISTRIB)/$$i; fi; done
 	cp *.c *.h $(MISC) $(DISTRIB)
 	rm -f $(DISTRIB)/sample.c
-	cp lib/* $(DISTRIB)/lib
+	mkdir $(DISTRIB)/data
+	cp data/*.* $(DISTRIB)/data/
+	for i in icons scripts stubs themes; do mkdir $(DISTRIB)/data/$$i; cp data/$$i/* $(DISTRIB)/data/$$i/; done
+	mkdir $(DISTRIB)/doc
+	cp doc/*.* $(DISTRIB)/doc
+	chmod +w $(DISTRIB)/doc/*
+	for i in doc/*.html; do sed 's/<title>Elvis[^ ]*/<title>Elvis-$(VERSION)/;s/ELVIS[^ <]*</ELVIS-$(VERSION)</' $$i >$(DISTRIB)/$$i; done
+	for i in doc/*.man; do sed 's/Elvis 2\.[0-9x][0-9a-z-]*/Elvis $(VERSION)/' $$i >$(DISTRIB)/$$i; done
 	for i in os*/*.c os*/*.h os*/*.mak os*/*.lib os*/*.ICO osos2/*.def osos2/*os2*; do cp $$i $(DISTRIB)/$$i; done
 	for i in gui*/*; do if [ -f $$i ]; then cp $$i $(DISTRIB)/$$i; fi; done
-	mkdir $(DISTRIB)/osos2/manual
-	mkdir $(DISTRIB)/osos2/manual/org
-	cp osos2/manual/*.ed osos2/manual/*.cmd $(DISTRIB)/osos2/manual/
 	rm -f $(DISTRIB)/osunix/osconfig.h
 	rm -f $(DISTRIB)/config.h
 	rm -f $(DISTRIB)/Makefile
-	rm -f $(DISTRIB)/lib/elvtags.man
+	rm -f $(DISTRIB)/doc/elvtags.man
+	rm -f $(DISTRIB)/doc/elvfmt.man
+	find $(DISTRIB) -type f -exec chmod +w {} \;
 	tar czf $(DISTRIB).tar.gz $(DISTRIB)
 	rm -rf $(DISTRIB)
 
 $(DISTRIB)-win32.tar.gz: $(WIN32EXE)
-	@[ -f $(WIN32EXE)/elvis.exe ] || (echo "You need to copy the *.exe files into $(WIN32EXE)"; exit 2)
 	rm -rf bin-win32
 	mkdir bin-win32
-	cp $(WIN32EXE)/*.exe bin-win32
+	cp $(WIN32EXE)/*.[eE][xX][eE] bin-win32
 	sed 's/$$//' <README.html >bin-win32/README.html
 	sed 's/$$//' <BUGS >bin-win32/BUGS
 	sed 's/$$//' <COPYING >bin-win32/COPYING
-	mkdir bin-win32/lib
-	cp lib/* bin-win32/lib
-	sed 's/$$//' <lib/printdoc.bat >bin-win32/lib/printdoc.bat
-	sed 's/$$//' <lib/license >bin-win32/lib/license
+	cp --recursive data bin-win32
+	cp --recursive doc bin-win32
+	chmod a+rw bin-win32/* bin-win32/*/* bin-win32/data/*/*
+	rm -rf bin-win32/data/RCS
+	rm -rf bin-win32/doc/RCS
+	showrgb | sed 's/ *\([0-9]\+\) *\([0-9]\+\) *\([0-9]\+\)[ 	]\+\(.*\)/\1	\2	\3	\4/; s/ //g' | tr '[A-Z]' '[a-z]' | sort -u +3 >bin-win32/data/rgb.txt
+	for i in doc/*.html; do sed 's/<title>Elvis[^ ]*/<title>Elvis-$(VERSION)/;s/ELVIS[^ <]*</ELVIS-$(VERSION)</' $$i >bin-win32/$$i; done
+	for i in doc/*.man; do sed 's/Elvis 2\.[0-9x][0-9a-z-]*/Elvis $(VERSION)/' $$i >bin-win32/$$i; done
+	sed 's/$$//' <doc/printdoc.bat >bin-win32/doc/printdoc.bat
+	sed 's/$$//' <doc/license.html >bin-win32/doc/license.html
+	sed 's/$$//' </usr/share/dict/words >bin-win32/data/words
+	(cd bin-win32/data/icons; xpm2ico *.xpm)
 	(cd bin-win32; tar czf ../$(DISTRIB)-win32.tar.gz *)
-	rm -rf bin-win32
 
-$(DISTRIB)-msdos.tar.gz: $(MSDOSEXE)
-	@[ -f $(MSDOSEXE)/elvis.exe ] || (echo "You need to copy the *.exe files into $(MSDOSEXE)"; exit 2)
+$(DISTRIB)-msdos.tar.gz: $(DOSEXE)
 	rm -rf bin-msdos
 	mkdir bin-msdos
-	cp $(MSDOSEXE)/*.exe bin-msdos
+	cp $(DOSEXE)/*.[eE][xX][eE] bin-msdos
 	sed 's/$$//' <README.html >bin-msdos/README.html
 	sed 's/$$//' <BUGS >bin-msdos/BUGS
 	sed 's/$$//' <COPYING >bin-msdos/COPYING
-	mkdir bin-msdos/lib
-	cp lib/* bin-msdos/lib
-	sed 's/$$//' <lib/printdoc.bat >bin-msdos/lib/printdoc.bat
-	sed 's/$$//' <lib/license >bin-msdos/lib/license
+	cp --recursive data bin-msdos
+	cp --recursive doc bin-msdos
+	chmod a+rw bin-msdos/* bin-msdos/*/* bin-msdos/data/*/*
+	rm -rf bin-msdos/data/RCS
+	rm -rf bin-msdos/doc/RCS
+	for i in doc/*.html; do sed 's/<title>Elvis[^ ]*/<title>Elvis-$(VERSION)/;s/ELVIS[^ <]*</ELVIS-$(VERSION)</' $$i >bin-msdos/$$i; done
+	for i in doc/*.man; do sed 's/Elvis 2\.[0-9x][0-9a-z-]*/Elvis $(VERSION)/' $$i >bin-msdos/$$i; done
+	sed 's/$$//' <doc/printdoc.bat >bin-msdos/doc/printdoc.bat
+	sed 's/$$//' <doc/license.html >bin-msdos/doc/license.html
 	(cd bin-msdos; tar czf ../$(DISTRIB)-msdos.tar.gz *)
-	rm -rf bin-msdos
 
 $(DISTRIB)-os2.tar.gz: $(OS2EXE)
-	@[ -f $(OS2EXE)/elvis.exe ] || (echo "You need to copy the *.exe files into $(OS2EXE)"; exit 2)
 	rm -rf bin-os2
 	mkdir bin-os2
-	cp $(OS2EXE)/*.exe bin-os2
+	cp $(OS2EXE)/*.[eE][xX][eE] bin-os2
 	sed 's/$$//' <README.html >bin-os2/README.html
 	sed 's/$$//' <BUGS >bin-os2/BUGS
 	sed 's/$$//' <COPYING >bin-os2/COPYING
-	mkdir bin-os2/lib
-	cp lib/* bin-os2/lib/
-	sed 's/$$//' <lib/printdoc.bat >bin-os2/lib/printdoc.bat
-	sed 's/$$//' <lib/printdoc.bat >bin-os2/lib/printdoc.cmd
-	sed 's/$$//' <lib/license >bin-os2/lib/license
-	cp osos2/elvis.INF bin-os2/lib/
-	mkdir bin-os2/osos2
-	cp osos2/README.os2 bin-os2/osos2/
+	cp --recursive data bin-os2
+	cp --recursive doc bin-os2
+	for i in doc/*.html; do sed 's/<title>Elvis[^ ]*/<title>Elvis-$(VERSION)/;s/ELVIS[^ <]*</ELVIS-$(VERSION)</' $$i >bin-os2/$$i; done
+	for i in doc/*.man; do sed 's/Elvis 2\.[0-9x][0-9a-z-]*/Elvis $(VERSION)/' $$i >bin-os2/$$i; done
+	sed 's/$$//' <doc/printdoc.bat >bin-os2/doc/printdoc.bat
+	sed 's/$$//' <doc/printdoc.bat >bin-os2/doc/printdoc.cmd
+	sed 's/$$//' <doc/license.html >bin-os2/doc/license.html
+	sed 's/$$//' </usr/dict/words >bin-os2/data/words
+	(cd bin-win32/data/icons; xpm2ico *.xpm)
+	cp osos2/elvis.INF bin-os2/data/
+	cp osos2/README.os2 bin-os2/doc/
+	chmod a-w bin-os2/data/* bin-os2/doc/*
 	(cd bin-os2; tar czf ../$(DISTRIB)-os2.tar.gz *)
-	rm -rf bin-os2
 
-lib$(SLASH)elvistrs.msg: $(SRCS)
-	sed -n '/%[cds]/d; s/\[[a-zA-Z]*\]//; s/\\\\/\\/g; s/.*msg(MSG_[A-Z]*, "\([^ 	"][^"]*\)".*/\1/p' *.c os*$(SLASH)*.c gui*$(SLASH)*.c | sort -u >lib$(SLASH)elvistrs.msg
+doc$(SLASH)elvistrs.msg: $(SRCS)
+	sed -n '/%[cds]/d; s/\[[a-zA-Z]*\]//; s/\\\\/\\/g; s/.*msg(MSG_[A-Z]*, "\([^ 	"][^"]*\)".*/\1/p' *.c os*$(SLASH)*.c gui*$(SLASH)*.c | sort -u >doc$(SLASH)elvistrs.msg
 
 ###############################################################################
 
 install: install.$(OS)
 
-install.unix: $(ALL)
-	rm -f lib/*.bak
+install.unix: $(ALL) doc/elvtags.man
+	rm -f doc/*.bak
+	[ -d $(BINDIR) ] || mkdir $(BINDIR)
 	cp $(ALL) $(BINDIR)
 	(cd $(BINDIR); chmod 0755 $(ALL))
-	mkdir -p $(LIBDIR) || test -d $(LIBDIR) || mkdir $(LIBDIR)
-	rm -f $(LIBDIR)/elvis*.
-	cp lib/* $(LIBDIR)
-	(cd lib; for i in *; do chmod 0644 $(LIBDIR)/$$i; done)
-	sh insticon.sh
-	sh instman.sh -b$(BINDIR) $(ALL)
+	rm -rf $(DATADIR)
+	mkdir -p $(DATADIR)
+	cp data/*.* $(DATADIR)
+	for i in icons scripts stubs themes; do mkdir $(DATADIR)/$$i; cp data/$$i/* $(DATADIR)/$$i/; done
+	rm -rf $(DOCDIR)
+	mkdir -p $(DOCDIR)
+	cp doc/*.html $(DOCDIR)
+	cp doc/*.man $(DOCDIR)
+	cp doc/*.txt $(DOCDIR)
+	cp doc/elvistrs.msg $(DOCDIR)
+	cp doc/printdoc.bat $(DOCDIR)
+	find $(DATADIR) -type f -exec chmod 0644 {} \;
+	find $(DOCDIR) -type f -exec chmod 0644 {} \;
+	(cd doc; for i in *.html; do sed 's/<title>Elvis[^ ]*/<title>Elvis-$(VERSION)/;s/ELVIS[^ <]*</ELVIS-$(VERSION)</' $$i >$(DOCDIR)/$$i; done)
+	(cd doc; for i in *.man; do sed 's/Elvis 2\.[0-9x][0-9a-z-]*/Elvis $(VERSION)/' $$i >$(DOCDIR)/$$i; done)
+	-(cd $(DATADIR); $(BINDIR)/elvtags -gitv stubs/*.c || ctags stubs/*.c)
+	chmod 0755 $(DATADIR)/*/. $(DATADIR) $(DOCDIR)
+	sh instman.sh -p$(PREFIX) $(ALL)
+	-[ -d /etc/elvis ] || mkdir /etc/elvis
+	-chmod 0755 /etc/elvis/
+	-@ : >/etc/elvis/README && ( \
+	  echo "This directory contains system-dependent versions of elvis' configuration" \
+	  echo "files.  The standard versions are available in $(DATADIR)"  \
+	  echo "To customize any of these configuration files for this system,"  \
+	  echo "first copy the standard version of the file into /etc/elvis and" \
+	  echo "then edit the copy.  Leave the standard version unchanged." \
+	) >>/etc/elvis/README
+	-chmod 0644 /etc/elvis/README
+	@echo "This directory contains the standard versions of elvis' configuration" >$(DATADIR)/README
+	@echo "files.  DO NOT MODIFY THESE FILES!  To perform host-specific customization," >>$(DATADIR)/README
+	@echo "copy files from this directory into /etc/elvis/, and then modify the copies." >>$(DATADIR)/README
+	@echo "To make user-specific changes, create a ~/.elvis/ directory (if it doesn't" >>$(DATADIR)/README
+	@echo "exist already) and copy files from this directory into ~/.elvis/ and then" >>$(DATADIR)/README
+	@echo "modify the copies.  Any file that elvis finds in ~/.elvis/ or /etc/elvis/" >>$(DATADIR)/README
+	@echo "overrides the similarly named file in this directory." >>$(DATADIR)/README
+	chmod 0644 $(DATADIR)/README
+
 
 ###############################################################################
 
@@ -380,7 +467,26 @@ uninstall: uninstall.$(OS)
 
 uninstall.unix:
 	(cd $(BINDIR); $(RM) $(ALL))
-	(cd lib; for i in *; do $(RM) $(LIBDIR)/$$i; done)
-	-rmdir $(LIBDIR)
-	sh insticon.sh -r 
-	sh instman.sh -r -b$(BINDIR) $(ALL)
+	rm -rf $(DATADIR)
+	rm -rf $(DOCDIR)
+	sh instman.sh -r -p$(PREFIX) $(ALL)
+
+###############################################################################
+
+elvis.rpm: elvis.spec.in $(DISTRIB).tar.gz
+	@topdir=`rpm --showrc|sed -n 's/%{_usrsrc}/\/usr\/src/;s/^[-0-9]*: _topdir[ 	]//p'`; \
+	 test -d $$topdir || topdir=/usr/src/redhat; \
+	 test -d $$topdir || topdir=/usr/src/packages; \
+	 echo topdir=$$topdir; \
+	 MANDIR=`sh instman.sh -d -p$(PREFIX)`; \
+	 if test -d $$topdir; \
+	 then \
+		 sed "s/VERSION/$(VERSION)/;s,MANDIR,$$MANDIR,g" elvis.spec.in >$$topdir/SPECS/elvis.spec; \
+		 cp $(DISTRIB).tar.gz $$topdir/SOURCES; \
+		 origdir=`pwd`; \
+		 cd $$topdir; \
+		 rpm -bb SPECS/elvis.spec && cp $$topdir/RPMS/i386/elvis-$(VERSION)-*.rpm $$origdir/elvis.rpm; \
+	 else \
+		 echo "Can't find rpm's topdir"; \
+		 exit 2; \
+	 fi
